In [2]:
import os
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request
import pyreadstat

In [21]:
rec_1, meta = pyreadstat.read_sav("../../_data/endes/2019/REC0111.sav")

In [22]:
rec_1

,ID1,HHID,CASEID,V001,V002,V003,V004,V007,V008,V009,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
0,2019.0,000100201,000100201 2,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.234450,2.0,7065.0
1,2019.0,000100201,000100201 3,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.234450,0.0,7065.0
2,2019.0,000102801,000102801 2,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.295611,2.0,7065.0
3,2019.0,000102801,000102801 6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,...,2.0,2.0,2.0,010101,3.0,154803.0,4.0,1.295611,2.0,7065.0
4,2019.0,000104801,000104801 2,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,...,2.0,2.0,2.0,010101,3.0,154803.0,2.0,-0.256431,2.0,7065.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,2019.0,325406201,325406201 2,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,...,2.0,2.0,2.0,250401,249.0,244995.0,1.0,-1.750187,2.0,15783.0
38331,2019.0,325406301,325406301 2,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,...,2.0,2.0,2.0,250401,249.0,244995.0,1.0,-1.676861,2.0,15783.0
38332,2019.0,325407001,325407001 2,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,...,2.0,2.0,2.0,250401,249.0,459792.0,1.0,-1.585333,2.0,15783.0
38333,2019.0,325407201,325407201 2,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,...,2.0,2.0,2.0,250401,249.0,459792.0,1.0,-1.650159,2.0,15783.0
38334,2019.0,325407401,325407401 2,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,...,2.0,2.0,2.0,250401,249.0,244995.0,1.0,-1.644720,2.0,15783.0

In [24]:
var_labels1= meta.column_names
value_labels1 = meta.column_labels

In [28]:
rec_1.keys()

Index(['ID1', 'HHID', 'CASEID', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008',
       'V009',
       ...
       'QD333_4', 'QD333_5', 'QD333_6', 'UBIGEO', 'V022', 'V005', 'V190',
       'V191', 'mujeres12a49', 'NCONGLOME'],
      dtype='object', length=105)

In [29]:
meta.variable_lables

AttributeError: 'metadata_container' object has no attribute 'variable_lables'